services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - /app/node_modules
